### ISSUE TITLE
No manifest update check

### ISSUE THREAD

**Issue by 48klocs** [sundevour/destiny2-manifest#4]
It could be way out of scope for the project, but the module doesn't check for updates when run - I had to purge the `./manifest` directory it creates to get it to pull the latest and greatest. In my case, I noticed that some newer items were being marked as invalid, and it took a little double-checking to realize that the problem was the months-old manifest I was using.

If nothing else, I'd suggest adding in a warning to the readme to purge manifest before you get started for the day's work.

**Comment by sundevour** [comment]
also an effect of how the tool in wishlist repo is coded. i will update it.
![image](https://user-images.githubusercontent.com/31990469/85357329-e9113f00-b4c5-11ea-80e3-d45a717f029b.png)
